import { Metadata } from "next";
import { Poppins } from "next/font/google";
import TodoListPage from "./todo/page";

export const metadata: Metadata = {
  title: "My - app",
  description: "Generated by create next app",
  authors: {
    name: "Muhammad Albas Tomi",
  },
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "700"],
});

export default function Home() {
  return (
    <main className={` ${poppins.className}`}>
      <TodoListPage />
    </main>
  );
}
